name: Blog Deploy

on:
  push:
    branches:
    - master

jobs:
    deploy:
        name: deploy to gh-pages
        runs-on: ubuntu-latest
        steps:
        - uses: gempir/blog@master
        - name: deploy
          run: |
              ./deploy.sh
